version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DBURL: postgres://koyeb-adm:npg_xOYiyzTdhZ64@ep-old-voice-a297zvqg.eu-central-1.pg.koyeb.app:5432/koyebdb
      DBUSERNAME: koyeb-adm
      DBPASSWORD: npg_xOYiyzTdhZ64
      DBNAME: koyebdb
